config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'main/index'

  get 'welcome/index'

  get 'search/results'

  get 'search/refer'

  resources :hospitals
  resources :beds

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
end

app/models/hospital.rb
class Hospital < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  # GET /beds
  # GET /beds.json
  def index
    @beds = Bed.all
  end

  # GET /beds/1
  # GET /beds/1.json
  def show
  end

  # GET /beds/new
  def new
    @bed = Bed.new
  end

  # GET /beds/1/edit
  def edit
  end

  # POST /beds
  # POST /beds.json
  def create
    @bed = Bed.new(bed_params)

    respond_to do |format|
      if @bed.save
        format.html { redirect_to @bed, notice: 'Bed was successfully created.' }
        format.json { render :show, status: :created, location: @bed }
      else
        format.html { render :new }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beds/1
  # PATCH/PUT /beds/1.json
  def update
    respond_to do |format|
      if @bed.update(bed_params)
        format.html { redirect_to @bed, notice: 'Bed was successfully updated.' }
        format.json { render :show, status: :ok, location: @bed }
      else
        format.html { render :edit }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beds/1
  # DELETE /beds/1.json
  def destroy
    @bed.destroy
    respond_to do |format|
      format.html { redirect_to beds_url, notice: 'Bed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bed
      @bed = Bed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bed_params
      params.require(:bed).permit(:room, :vacant, :price, :tier, :hospital_id)
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :contact, :hospital_id, :distance)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @hospital = Hospital.first
    arr_beds_current = Bed.where "hospital_id = ? AND vacant = ?", @hospital.hospital_id, false
    arr_beds_total = Bed.where hospital_id: @hospital.hospital_id
    @beds_current = arr_beds_current.length
    @beds_total = arr_beds_total.length
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @options = ["Service Ward", "Semi-Private Room", "Private Room", "ICU"]
  end

  def refer
    @target = params[:target]
    @hospitals = Hospital.where.not hospital_id: Hospital.first.hospital_id
    new_hospitals = []
    @hospitals.each do |hospital|
      bed_count_total = Bed.where "hospital_id = ? AND tier = ?", hospital.hospital_id, @target
      bed_count_curr = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", hospital.hospital_id, @target, false
      if bed_count_curr.length == bed_count_total.length
        next
      end
      new_hospitals.push(hospital)
    end
    @hospitals = new_hospitals
    @hospitals = @hospitals.sort_by {|hospital| hospital.distance}
  end

  def results
    @raw_type = params[:tier]
    if @raw_type == "Service Ward"
      room_id = "service"
    elsif @raw_type == "Semi-Private Room"
      room_id = "semi"
    elsif @raw_type == "Private Room"
      room_id = "private"
    elsif @raw_type == "ICU"
      room_id = "icu"
    end

    @beds = Bed.where "hospital_id = ? AND vacant = ? AND tier = ?", Hospital.first.hospital_id, true, room_id

    if @beds.length == 0
      redirect_to search_refer_url target:room_id
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beds/_form.html.erb
<%= form_with(model: bed, local: true) do |form| %>
  <% if bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% bed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room, id: :bed_room %>
  </div>

  <div class="field">
    <%= form.label :vacant %>
    <%= form.check_box :vacant, id: :bed_vacant %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :bed_price %>
  </div>

  <div class="field">
    <%= form.label :tier %>
    <%= form.text_field :tier, id: :bed_tier %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.text_field :hospital_id, id: :bed_hospital_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beds/edit.html.erb
<h1>Editing Bed</h1>

<%= render 'form', bed: @bed %>

<%= link_to 'Show', @bed %> |
<%= link_to 'Back', beds_path %>

app/views/beds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beds</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Vacant</th>
      <th>Price</th>
      <th>Tier</th>
      <th>Hospital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beds.each do |bed| %>
      <tr>
        <td><%= bed.room %></td>
        <td><%= bed.vacant %></td>
        <td><%= bed.price %></td>
        <td><%= bed.tier %></td>
        <td><%= bed.hospital_id %></td>
        <td><%= link_to 'Show', bed %></td>
        <td><%= link_to 'Edit', edit_bed_path(bed) %></td>
        <td><%= link_to 'Destroy', bed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bed', new_bed_path %>

app/views/beds/new.html.erb
<h1>New Bed</h1>

<%= render 'form', bed: @bed %>

<%= link_to 'Back', beds_path %>

app/views/beds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @bed.room %>
</p>

<p>
  <strong>Vacant:</strong>
  <%= @bed.vacant %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bed.price %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @bed.tier %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @bed.hospital_id %>
</p>

<%= link_to 'Edit', edit_bed_path(@bed) %> |
<%= link_to 'Back', beds_path %>

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hospital_name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_area :contact, id: :hospital_contact %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.text_field :hospital_id, id: :hospital_hospital_id %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance, id: :hospital_distance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Hospital</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.contact %></td>
        <td><%= hospital.hospital_id %></td>
        <td><%= hospital.distance %></td>
        <td><%= link_to 'Show', hospital %></td>
        <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @hospital.contact %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @hospital.hospital_id %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @hospital.distance %>
</p>

<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js' %>
    
  </head>

  <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #09859f">
      <a class="navbar-brand" href="#">trace</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <i class="fa fa-search" style="color:white"></i>
          </li>

          <!--
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        -->

        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Trace</title>
</head>

<body>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="container-fluid align-middle rounded bg-white container-main">

        <div class="container">

        <%= yield %>
        <!-- Example row of columns -->
        <div class="row">
        <div class="col-md-4">
            <h4 class="text-center"><%=@hospital.name%></h4>
            <h6 class="text-center">Hospital Name</h6>
        </div>
        <div class="col-md-4">
            <h4 class="text-center"><%=@hospital.contact%></h4>
            <h6 class="text-center">Contact</h6>
        </div>
        <div class="col-md-4">
            <h4 class="text-center"><%=@beds_current%> / <%=@beds_total%></h4>
            <h6 class="text-center">Total Occupied Beds</h6>
        </div>
        </div>

        <hr>

        <div class="container">
          <h5 class="text-center">
            <%arr_service = Bed.where "hospital_id = ? AND tier = ?", @hospital.hospital_id, "service"%>
            <%arr_semi = Bed.where "hospital_id = ? AND tier = ?", @hospital.hospital_id, "semi"%>
            <%arr_private = Bed.where "hospital_id = ? AND tier = ?", @hospital.hospital_id, "private"%>
            <%arr_icu = Bed.where "hospital_id = ? AND tier = ?", @hospital.hospital_id, "icu"%>

            <%arr_service_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", @hospital.hospital_id, "service", false%>
            <%arr_semi_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", @hospital.hospital_id, "semi", false%>
            <%arr_private_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", @hospital.hospital_id, "private", false%>
            <%arr_icu_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", @hospital.hospital_id, "icu", false%>

            <div class="container">
              Occupied Service Wards : <%=arr_service_c.length%> / <%=arr_service.length%>
            </div>
            <div class="container">
              Occupied Semi-Private Rooms : <%=arr_semi_c.length%> / <%=arr_semi.length%>
            </div>
            <div class="container">
              Occupied Private Rooms : <%=arr_private_c.length%> / <%=arr_private.length%>
            </div>
            <div class="container">
              Occupied Intensive Care Units : <%=arr_icu_c.length%> / <%=arr_icu.length%>
            </div>
          </h5>
        </div>

        </div>

    </main>

    <br><br>
    <div class="text-center"> 
        <%=button_to "Search For a Room", search_index_path, :method => "get", :class => "btn btn-primary btn-lg"%>
    </div>

</body>
</html> 

app/views/search/index.html.erb
<div class="text-center">

  <div class="container align-middle bg-white rounded container-dialog">
    <div class="container">
      <div class="form-group">
      <%= form_tag search_results_url, method: :get do %>
        <h1 class="search-label">Room Type:</h1>
        <%= select_tag :tier, options_for_select(@options, "Service Ward"), :class => "form-control"%> <br>
        <%= submit_tag "Search Now", :class => "btn btn-primary", :id => "sub-btn"%>
      <% end %>
      </div>
    </div>
  </div>

</div>

app/views/search/refer.html.erb
<div class="container align-middle bg-white rounded container-dialog">
    <div class="container">
      <div class="form-group">
        <h1 class="text-center">There are no more vacancies.</h1>

        <hr>
        <h5 class="text-center"> Please refer the patient to one of the hospitals below: </h5>
        <hr>
        
        <h5 class="text-center">
        <% @hospitals.each do |hospital| %>

        <div class="results-container rounded">
        <% arr_bed_service = Bed.where "hospital_id = ? AND tier = ?", hospital.hospital_id, "service" %>
        <% arr_bed_semi = Bed.where "hospital_id = ? AND tier = ?", hospital.hospital_id, "semi" %>
        <% arr_bed_private = Bed.where "hospital_id = ? AND tier = ?", hospital.hospital_id, "private" %>
        <% arr_bed_icu = Bed.where "hospital_id = ? AND tier = ?", hospital.hospital_id, "icu" %>
        <% arr_bed_service_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", hospital.hospital_id, "service", false %>
        <% arr_bed_semi_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", hospital.hospital_id, "semi", false %>
        <% arr_bed_private_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", hospital.hospital_id, "private", false %>
        <% arr_bed_icu_c = Bed.where "hospital_id = ? AND tier = ? AND vacant = ?", hospital.hospital_id, "icu", false %>

        <strong> <%= hospital.name %> </strong> <br>
        <h6><%= hospital.distance %> km away</h6> <br> 
        <strong>Occupied Service Rooms:</strong> <%= arr_bed_service_c.length+30%> / <%= arr_bed_service.length+30 %> <br>
        <strong>Occupied Semi-Private Rooms:</strong> <%= arr_bed_semi_c.length+20%> / <%= arr_bed_semi.length+20 %> <br>
        <strong>Occupied Private Rooms:</strong> <%= arr_bed_private_c.length+10%> / <%= arr_bed_private.length+10 %> <br>
        <strong>Occupied ICU Rooms:</strong> <%= arr_bed_icu_c.length+5%> / <%= arr_bed_icu.length+5 %> <br>
        <strong>Contact:</strong> <%= hospital.contact %> <br>
        </div>

        <% end %>
        
        <hr>
        <%# back button here: %>
        <%= button_to "Back", main_index_path, :class => "btn btn-primary", :method => "get"%>
        </h5>
      </div>
    </div>
</div>

app/views/search/results.html.erb
<div class="container align-middle bg-white rounded container-dialog">
    <div class="container">
      <div class="form-group">
        <div class="text-center">
            <h1>There are available rooms.</h1>
            <hr>
            
            <h5>
            <% @beds.each do |bed| %>
                <div class="results-container rounded text-left">
                    <strong>Room No.</strong> <%= bed.room %> (<%= @raw_type %>) |
                    <strong>Price:</strong> <%= bed.price %> Php/Day
                </div>
            <% end %>
            
            <hr>
            <%# back button here: %>
            <%= button_to "Back", main_index_path, :class => "btn btn-primary", :method => "get"%>
            </h5>
            
        </div>
      </div>
    </div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Trace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

    <div class="text-center">
      <%= image_tag 'tracefin-01.png', :class => "navbar-brand" %>
      <p class="tagline">Leave a good trace.</p>
    </div>
    <br><br>
    <div class="container">
        <h2 class="text-center"><%= button_to "ENTER", "main/index", :class => "btn btn-primary btn-lg", :method => "get"%></h2>
    </div>

</body>
</html>